### ISSUE TITLE
Query: -Sh option behavior with network mapped drive

### ISSUE THREAD

**Issue by viralmutant** [microsoft/diskspd#121] opened 2019-09-19 18:06 UTC
I am trying to enable 'Write-through' and no software caching on a network mapped drive.

`    ...\DiskSpd-2.0.21a\amd64>diskspd -b8K -d30 -o4 -t8 -Suw -r -w25 -L -Z20G -c1G y:\iotest.dat > DiskSpeedResults.txt`
`WARNING: Could not set valid file size (error code: 87); trying a slower method of filling the file (this does not affect performance, just makes the test preparation longer)`

But the network trace shows 'Create' request with 'WRITE_THROUGH' flag as '0' in 'Create options'

Is this expected or am I doing something wrong ?

**Comment by dl2n** [comment] 2020-02-24 21:03
Is this question still open?

**Comment by viralmutant** [comment] 2020-02-25 21:08
> Is this question still open?

Yes

**Comment by dl2n** [comment] 2020-02-26 01:28
I suspect you're looking at the create for the slow fill, not the create for the measured load test. If you look at the trace you should see a second SMB2 Create which will have the writethrough/nointermediatebuffering CreateOptions flags set.

The slow fill's create is indeed not following the specification for the measured run; this is in IORequestGenerator::_CreateFile. This shouldn't affect the run - a reasonable implementation (and all Windows clients/servers) will guarantee the cache on both sides will be flushed through and torn down during the second Create, and the IO will regardless run as intended. There is the very small chance that a second open of the file could come in and hold the cache section open, which would create very noticeable effects due to cache coherency flush/purge. However, this is a very small chance, and if there is a second process sneaking in to try to create this condition there is nothing DISKSPD can do about it.

It does probably help speed up the slow fill process for the majority of cases so I'm reluctant to change this.

**Comment by dl2n** [comment] 2020-02-26 01:28
You should also be able to confirm that the file handle the measured IO is coming through is the unbuffered/writethrough one.

**Comment by dl2n** [comment] 2021-11-02 17:46
Closing old q&a issue.

**Closed by dl2n** 2021-11-02 17:46 UTC
