### ISSUE TITLE
Compilation fails under Visual Studio 2017.2

### ISSUE THREAD

**Issue by jrp2014** [Microsoft/diskspd#41] opened 2017-08-13 21:16 UTC
The XSD steps fail, even after to new toolset and SDK 10.

**Comment by DanPear** [comment] 2017-11-01 13:27
The condition is due to a dependency that xsd.exe has on CppCodeProvider.dll. As Visual Studio 2017 installs CppCodeProvider.dll into a different location, XSD can't locate the DLL in either the GAC or the NETFX directory for the targeted Windows SDK. You can work around the problem by running the following command from within a Developer Command Prompt:

`GacUtil /i "%DevEnvDir%\PublicAssemblies\CppCodeProvider.dll"`

**Comment by dl2n** [comment] 2017-11-01 16:54
Thanks Daniel. How would we fix this in the project itself?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by DanPear** [comment] 2017-11-01 21:40
On closer inspection it appears as if the reference in the XmlProfileParser project isn't required as diskspd.xsd is included as a resource inside of CmdRequestCreator.vcxproj. That way the XML Schema Definition Tool never needs to run.

**Comment by DanPear** [comment] 2018-05-01 23:58
This issue has been addressed in a48cc0d3613d23459f436a476b436a113146aeb7 and confirmed as working.

**Closed by DanPear** 2018-05-01 23:58 UTC
